### ISSUE TITLE
generate generic service from blast.yml

### ISSUE THREAD

**Issue by PapsOu** [blast-project/CoreBundle#23]
FEATURE REQUEST

Add the ability to define and generate generic service when using the GenericAdmin class for basic entity admin.

Here the use case :

- I want to create a really basic admin for a basic entity
- I define the blast.yml entry as usual

Expected result :

The admin should be accessible out of the box (without creating the sonata service manualy)

Example of blast.yml :

```yaml
        Librinfo\EcommerceBundle\Entity\Zone:
            baseRoute: 
                name: admin_librinfo_ecommerce_zone
                pattern: librinfo/ecommerce/zone
            generateGenericService: true
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    name: ~
                    code: ~
                    type: ~
                    scope: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    '':
                        form_group_general:
                            name: ~
                            code: ~
                            type: ~
                            scope: ~
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name: ~
                    code: ~
                    type: ~
                    scope: ~
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    name: ~
                    code: ~
                    type: ~
                    scope: ~
```

The admin should be available when going to this URL : [adminPrefix]/librinfo/ecommerce/zone/list
