### ISSUE TITLE
Auto add type on blast.yml

### ISSUE THREAD

**Issue by FanchTheSystem** [blast-project/CoreBundle#47]
example:

 createdAt: ~

become

```
  createdAt: 
                                type: sonata_type_datetime_picker
                                attr:
                                    readonly: true
                                disabled: true
                                required: false
                                dp_side_by_side: true

```
